name: Build and Test
on:
  push:
    branches-ignore:
      - 'main'
    tags-ignore:
      - '**'
  pull_request:
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - uses: golangci/golangci-lint-action@v3
      - name: Docker login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build
        run: go build .
      - name: Tests.
        run: go test