name: Build and Test
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.33
      - name: Build
        run: go build .
      - name: Tests.
        run: go test
  docker:
    name: Build docker image
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u USERNAME --password-stdin
      - name: Publish docker
        run: |
          VERSION=$(echo "$GITHUB_REF" | sed -e 's,.*/\(.*\),\1,')
          IMAGE_ID=ghcr.io/$GITHUB_REPOSITORY:$VERSION
          docker build -t $IMAGE_ID --build-arg VERSION=$VERSION -f docker/Dockerfile .
